export const products = [
  {
    name: '樱花垂坠耳环',
    description: '以樱花为灵感，925银手工雕刻，轻盈垂坠，展现日式优雅。',
    longDescription: '这款耳环采用925纯银，由工匠逐朵手工雕刻樱花纹样，每一片花瓣的弧度都经过精心打磨。佩戴时随动作轻轻摇曳，如同春风中飘落的花瓣，传递"一期一会"的美好意境。',
    price: 1280, imageUrls: ['/images/placeholder.jpg'], category: '耳环',
    featured: true, inStock: 15, material: '925纯银', technique: '手工雕刻',
    dimensions: '长3.5cm', weight: '4g', tags: ['樱花', '垂坠', '日式', '精选'], rating: 4.9, reviewCount: 32,
  },
  {
    name: '月见草耳钉',
    description: '月见草花型设计，镶嵌天然贝母，简约而不失精致。',
    longDescription: '月见草象征着沉静与内敛之美。这款耳钉以月见草为原型，花芯镶嵌天然贝母，在光线下散发柔和的珍珠光泽。小巧精致，适合日常佩戴，也是送礼的绝佳之选。',
    price: 880, imageUrls: ['/images/placeholder.jpg'], category: '耳环',
    featured: false, inStock: 20, material: '925纯银 + 天然贝母', technique: '镶嵌工艺',
    dimensions: '直径1.2cm', weight: '2.5g', tags: ['月见草', '耳钉', '贝母', '日常'], rating: 4.7, reviewCount: 18,
  },
  {
    name: '金箔和纸耳环',
    description: '融合日本和纸与金箔工艺，轻若鸿毛，独一无二。',
    longDescription: '将传统日本和纸工艺与首饰设计融合，每张和纸经过特殊防水处理后贴附金箔，轻盈如羽毛。每一对都是独一无二的艺术品，适合追求个性与文化深度的佩戴者。',
    price: 1560, imageUrls: ['/images/placeholder.jpg'], category: '耳环',
    featured: true, inStock: 8, material: '和纸 + 金箔 + 钛钢耳钩', technique: '和纸工艺 + 金箔贴饰',
    dimensions: '长4cm', weight: '1.5g', tags: ['和纸', '金箔', '艺术', '限量'], rating: 5.0, reviewCount: 11,
  },
  {
    name: '竹节系列戒指',
    description: '以竹节为造型，925银精铸，寓意节节高升，清雅脱俗。',
    longDescription: '竹在日本文化中象征坚韧与高洁。这款戒指将竹节的自然形态抽象提炼，采用失蜡铸造工艺精心制作，表面经过哑光处理，质感温润如玉。既可单独佩戴，亦可多枚叠戴。',
    price: 1980, imageUrls: ['/images/placeholder.jpg'], category: '戒指',
    featured: true, inStock: 12, material: '925纯银', technique: '失蜡铸造 + 哑光处理',
    dimensions: '可定制尺码 6-18号', weight: '5.5g', tags: ['竹节', '戒指', '日式', '精选'], rating: 4.8, reviewCount: 27,
  },
  {
    name: '海浪纹戒指',
    description: '日本传统青海波纹样，富士山与海浪交融，层次分明。',
    longDescription: '青海波是日本最古老的传统纹样之一，象征着平和与永恒。这款戒指将青海波纹样以微雕形式呈现于银环之上，每一波浪都清晰可见，工艺精细入微，展现工匠的极致追求。',
    price: 2380, imageUrls: ['/images/placeholder.jpg'], category: '戒指',
    featured: false, inStock: 7, material: '925纯银', technique: '微雕工艺',
    dimensions: '可定制尺码 6-18号', weight: '6g', tags: ['青海波', '传统纹样', '微雕', '工艺'], rating: 4.9, reviewCount: 15,
  },
  {
    name: '鹤鸣项链',
    description: '祥鹤展翅，寓意长寿与祥瑞，纯银打造，气质出众。',
    longDescription: '鹤在日本文化中是长寿与吉祥的象征。这款项链将飞翔的仙鹤以立体雕塑形式呈现，翅膀的每根羽毛都清晰分明。搭配45cm纯银链，可调节长度，适合各种领口。',
    price: 2980, imageUrls: ['/images/placeholder.jpg'], category: '项链',
    featured: true, inStock: 10, material: '925纯银', technique: '3D立体铸造 + 手工打磨',
    dimensions: '吊坠3×4cm，链长45cm可调', weight: '12g', tags: ['鹤', '项链', '吉祥', '精选'], rating: 4.9, reviewCount: 41,
  },
  {
    name: '枯山水项链',
    description: '抽象表现禅意枯山水，简约线条蕴含深远意境。',
    longDescription: '枯山水是日本禅文化的精髓，以石头和砂砾诠释山水意境。这款项链将枯山水的几何美学凝练为一块小小的银质吊坠，极简的线条中蕴含着"侘寂"哲学。',
    price: 1680, imageUrls: ['/images/placeholder.jpg'], category: '项链',
    featured: false, inStock: 18, material: '925纯银', technique: '激光雕刻 + 手工磨砂',
    dimensions: '吊坠2×2.5cm，链长40-45cm', weight: '8g', tags: ['枯山水', '禅意', '极简', '日式'], rating: 4.6, reviewCount: 22,
  },
  {
    name: '源氏香手链',
    description: '以平安时代源氏香纹为设计元素，银编绳链工艺精湛。',
    longDescription: '源氏香是平安时代宫廷中流行的香道游戏，其纹样简洁而富有变化。这款手链将源氏香纹样点缀于精编银链之上，如诗如歌，雅韵悠长。',
    price: 2180, imageUrls: ['/images/placeholder.jpg'], category: '手链手镯',
    featured: true, inStock: 9, material: '925纯银', technique: '编链工艺 + 微铸吊坠',
    dimensions: '周长16cm可调', weight: '8g', tags: ['源氏香', '手链', '平安', '日式'], rating: 4.8, reviewCount: 19,
  },
  {
    name: '祭典手镯',
    description: '以日本祭典为灵感，金银双色交织，节日喜庆。',
    longDescription: '每逢夏日祭典，人们身着浴衣佩戴各式饰品。这款手镯以祭典灯笼和烟火为装饰元素，金银两色交织，宽度适中，佩戴时既有存在感又不失优雅。',
    price: 1880, imageUrls: ['/images/placeholder.jpg'], category: '手链手镯',
    featured: false, inStock: 14, material: '925纯银 + 18K镀金', technique: '双色电镀 + 手工錾刻',
    dimensions: '内径6cm', weight: '18g', tags: ['祭典', '手镯', '金银', '夏日'], rating: 4.7, reviewCount: 13,
  },
  {
    name: '松竹梅胸针',
    description: '松竹梅"岁寒三友"，925银精雕，镶翠色碧玺，吉祥如意。',
    longDescription: '松、竹、梅并称"岁寒三友"，是坚韧与高洁的象征。这款胸针以松竹梅为构图，主体925银精雕，点缀天然碧玺和白水晶，精致华贵，适合重要场合佩戴。',
    price: 3680, imageUrls: ['/images/placeholder.jpg'], category: '胸针',
    featured: true, inStock: 5, material: '925纯银 + 碧玺 + 白水晶', technique: '精密铸造 + 宝石镶嵌',
    dimensions: '5×6cm', weight: '22g', tags: ['松竹梅', '胸针', '宝石', '吉祥'], rating: 5.0, reviewCount: 8,
  },
  {
    name: '蝴蝶胸针',
    description: '拟真蝴蝶设计，彩色珐琅点彩，栩栩如生，灵动飞翔。',
    longDescription: '蝴蝶象征着蜕变与自由。这款胸针以金属骨架为基础，每片翅膀精心填充彩色珐琅，色彩层次丰富。翅膀可以微微颤动，佩戴时仿佛真正的蝴蝶在衣间休憩。',
    price: 2280, imageUrls: ['/images/placeholder.jpg'], category: '胸针',
    featured: false, inStock: 11, material: '925纯银 + 彩色珐琅', technique: '珐琅点彩 + 手工着色',
    dimensions: '7×5cm', weight: '15g', tags: ['蝴蝶', '珐琅', '彩色', '灵动'], rating: 4.8, reviewCount: 24,
  },
  {
    name: '京都秋韵套装',
    description: '耳环+项链+手链三件套，枫叶纹样，深秋风情，礼盒包装。',
    longDescription: '深秋的京都，漫山红枫如火如霞。这套首饰以京都秋枫为主题，耳环、项链、手链三件套形成统一的设计语言。925纯银基底，表面镀玫瑰金，枫叶细节精致入微。',
    price: 5980, imageUrls: ['/images/placeholder.jpg'], category: '套装',
    featured: true, inStock: 6, material: '925纯银 + 玫瑰金镀层', technique: '精密铸造 + 玫瑰金电镀',
    dimensions: '耳环3cm / 项链45cm / 手链16cm', weight: '28g（套装）', tags: ['套装', '枫叶', '京都', '礼盒', '精选'], rating: 4.9, reviewCount: 36,
  },
  {
    name: '雪月花套装',
    description: '雪、月、花三重意境，项链+耳环二件套，四季之美尽在其中。',
    longDescription: '"雪月花"是日本传统美学中最具代表性的意象。这款套装将三种意象分别演绎于项链吊坠与耳环之上，整体协调统一，兼顾日常与正式场合。',
    price: 4380, imageUrls: ['/images/placeholder.jpg'], category: '套装',
    featured: false, inStock: 8, material: '925纯银', technique: '手工雕刻 + 磨砂处理',
    dimensions: '吊坠2.5cm / 耳环2cm / 项链42cm', weight: '20g（套装）', tags: ['套装', '雪月花', '四季', '日式'], rating: 4.7, reviewCount: 17,
  },
];

export const adminUser = {
  name: '柏木杏子',
  email: 'admin@kashiwagi-design.com',
  password: 'Admin123456',
  role: 'admin' as const,
};
